server:
  port: ${PORT:8082}

api:
  key: ${API_KEY}

spring:
  application:
    name: product-service
  profiles:
    active: ${ACTIVE_PROFILE:oauth2} # basic-auth oauth2, apikey, mTLS

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        generate_statistics: ${HIBERNATE_GENERATE_STATISTICS:false}
  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}
    driver-class-name: ${PRODUCT_DB_DRIVER_CLASS_NAME}

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URL}

