spring:
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_flywaydb
    username: 'product_service_flywaydb_user'
    password: 'product_service_flywaydb'
    driver-class-name: com.mysql.cj.jdbc.Driver
